apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: hostpath-provisioner
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        app: hostpath-provisioner
    spec:
      serviceAccountName: hostpath-provisioner
      containers:
        - name: hostpath-provisioner
          # image: mazdermind/hostpath-provisioner
          image: cunal/hostpath-provisioner:v0.1.0
          imagePullPolicy: Always
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: PV_DIR
              value: /tmp
          volumeMounts:
            - name: pv-volume
              mountPath: /tmp
      volumes:
        - name: pv-volume
          hostPath:
            path: /tmp
