kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: hostpath-test-claim
  namespace: default
spec:
  storageClassName: "hostpath"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
